# Generated by Django 5.1.2 on 2024-11-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likers',
        ),
    ]
