# Generated by Django 5.1.2 on 2024-11-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_likes_post_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
    ]
