# Generated by Django 5.1.2 on 2024-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
