# Generated by Django 5.1.2 on 2024-11-02 06:58

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=user.models.construct_path),
        ),
    ]
