# Generated by Django 5.1.2 on 2025-01-03 07:12

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_photo',
            field=models.ImageField(null=True, upload_to=user.models.construct_background_path),
        ),
    ]
