# Generated by Django 5.1.2 on 2024-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_date_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='previewed',
            field=models.BooleanField(default=False),
        ),
    ]
